Lesson2
Vladislav23R/geekshop pull request #2
Opened 2021-06-01 14:56 UTC by Vladislav23R

2021-06-01 18:20 UTC, Vokler requested changes

2021-06-01 18:20 UTC, Vokler commented on products/templates/products/products.html
> +                {% if products %}
Было бы тогда отлично добавить else и выводить сообщение о том, что товаров нет

2021-06-01 22:42 UTC, Vladislav23R commented on products/templates/products/products.html
> +                {% if products %}
На 106 строке прописан else.

2021-06-02 07:58 UTC, Vokler approved these changes

2021-06-02 07:58 UTC, merged