Lesson3
Vladislav23R/geekshop pull request #3
Opened 2021-06-02 17:46 UTC by Vladislav23R

2021-06-03 07:25 UTC, Vokler requested changes

2021-06-03 07:25 UTC, Vokler commented on geekshop/settings.py
> +LANGUAGE_CODE = 'ru-us'
Если меняете на русский, то тогда уже `ru-ru`

2021-06-03 07:25 UTC, Vokler commented on products/views.py
>      context = {
Добавьте сюда еще вывод категорий. Они у вас в шаблоне есть, поэтому стоит там убрать захардкорженные моменты

2021-06-03 15:09 UTC, Vladislav23R commented on products/views.py
>      context = {
добавил вывод категорий

2021-06-04 07:53 UTC, Vokler approved these changes

2021-06-04 07:53 UTC, merged